version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: data_base
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nbhvbn23
      POSTGRES_DB: vacancieshh
    volumes:
      - ./data:/data
    ports:
      - 5432:5432

  back:
    build:
      context: backend/
    container_name: back_app
    env_file:
      - .env
    ports:
      - 7419:7419
    depends_on:
      - db

  front:
    build:
      context: front/
    container_name: front_app
    ports:
      - 8000:8000
    depends_on:
      - back